agr

diff --git a/.github/workflows/PR.yaml b/.github/workflows/PR.yaml
--- a/.github/workflows/PR.yaml
+++ b/.github/workflows/PR.yaml
@@ -73,7 +73,8 @@ jobs:
         id: pr-body
         run: |
           # Run the pr_body.py script with the missing features data
-          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/pr_body.py missing_features.json)
+          PR_BODY_CONTENT=$(python src/scribe_data/check/check_missing_forms/pr_body.py query_check_missing_features.json) || echo "No missing features/forms found."
+
 
           # Debug output
           echo "PR Body Content:"
@@ -91,6 +92,7 @@ jobs:
           echo "PR Body from GITHUB_OUTPUT:"
           cat $GITHUB_OUTPUT
       - name: Create Pull Request
+        if: steps.pr-body.outputs.body != 'No missing features/forms found.'
         uses: peter-evans/create-pull-request@v5
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
